### ISSUE TITLE
Combined shortcut with Meta key not working

### ISSUE THREAD

**Issue by ligne13** [monsterbrain/keyboard-shortcut-image-generator#2]
Hi,
I need to generate an image of the shortcut Cmd + S but it does not work when I press the meta key(there is no + sign waiting for the next key):

![Capture d’écran 2020-09-02 à 18 16 52](https://user-images.githubusercontent.com/81624/92009227-7c79b280-ed48-11ea-84a5-ff11f9a31dc3.png)

**Comment by monsterbrain** [comment]
Thanks for posting the issue. Are you using a mac keyboard ? Is that meta + something is sufficient or Do you want me to replace it with Ctrl / CMD ? I'll look into it.

**Comment by ligne13** [comment]
@monsterbrain yes I'm using a Mac keyboard.
Meta + key is enough for now. But it would be great to be able to choose wether to use Ctrl/Meta + key !

great app !

**Comment by monsterbrain** [comment]
![image](https://user-images.githubusercontent.com/10105094/92095041-c919c800-edf2-11ea-9cfa-c6c764158b5a.png)

Is this fine ? Also, when you press cmd + some key, will it override any system functions (so that the key is never registered in the browser)

**Comment by ligne13** [comment]
Yes it's good. However in your screenshot the selected OS is Windows, shouldn't it be Mac ?

And yes, you have to override system functions in your app to allow Cmd+... shortcut

**Comment by monsterbrain** [comment]
Yes. Windows is for testing purposes ( I only have windows). I might have to use a toggle button for keys like (Windows / CMD/ Tab) etc so that shortcuts using that could be implemented better ... (For eg. CMD + M will minimize the window I think). Thanks ..

**Comment by monsterbrain** [comment]
![image](https://user-images.githubusercontent.com/10105094/92193160-4130ce00-ee85-11ea-8fb8-90a5882ad858.png)

New update is up. Thanks for posting the issue.
