### ISSUE TITLE
Please allow us to define the Key-Names by entering Text

### ISSUE THREAD

**Issue by schittli** [monsterbrain/keyboard-shortcut-image-generator#3]
Thank you very much for this great Tool!,
could you please add `Text` as an additional Option?:

```
OS: 🔘 Windows 🔘 Mac 🔘 Other 🔘 Text
```

This would allow us to define Keyboard Shortcuts:
- with exactly the same Text as the Keys are labelled 
- we could create Shortcuts for Keys which the _keyboard-shortcut-image-generator_ does not know
- we could create Shortcuts for Keys which we can not enter in the Textbox because the OS captures them
- we could create multi-level Shortcuts, e.g. Ctrl + Shift a,b (`a` followed by `b`)

For example:
- `Ctrl + Esc`
- `Ctrl + PgUp`
- `Ctrl + Win + D`
- `Ctrl + Shift + A, B` _» (`a` followed by `b`)_
- …

Thanks a lot! kind regards,
Thomas

**Comment by monsterbrain** [comment]
Sure. I can add that. I'll try adding it as soon as possible. Remind me plz if I'm being lazy after 2 days... :)

**Comment by monsterbrain** [comment]
Hi @schittli , 

The new text input is live now ... please check
