### ISSUE TITLE
Windows + key is overriden by the OS

### ISSUE THREAD

**Issue by rgkey9000** [monsterbrain/keyboard-shortcut-image-generator#5]
How to create shortcuts that include a windows key like Windows+R (RUN)

**Comment by monsterbrain** [comment]
![image](https://user-images.githubusercontent.com/10105094/198180425-401f5a3f-08bf-4308-a6ed-e1c2bc11991c.png)
You can click the Windows button and Press R.

**Comment by rgkey9000** [comment]
The moment I press the WIN key, the focus shifts towards the start button, clicking back, resets the field. I used the 'Text' field now, that worked great.
