### ISSUE TITLE
Suggestion: adding CTRL key as button (like the system key)

### ISSUE THREAD

**Issue by Nootilus** [monsterbrain/keyboard-shortcut-image-generator#6]
Hello!

Nice life saving tool for me :)
One small issue/suggestion: put the CTRL (and maybe some other system keys) as a graphic button, like you did with the system (win/cmd) key so you can add is easily without triggering any system shortcut.

For example, I’m not unable to generate the image for `ctrl + N` shortcut as it triggers the opening of a new window in my browser.

**Comment by monsterbrain** [comment]
Sure. I can do that .. Thanks for the suggestion..

**Comment by monsterbrain** [comment]
I've added the feature .. not only Ctrl but also Alt also ..

![image](https://user-images.githubusercontent.com/10105094/201317266-e6d3d3d4-af81-4452-bde4-3678217bd70b.png)

THanks for the suggestion and enjoy .. feel free to suggest more ..
