### ISSUE TITLE
"Alt" and "Alt Gr" and Whitespaces

### ISSUE THREAD

**Issue by TsgabiXD** [monsterbrain/keyboard-shortcut-image-generator#8]
Since you cannot press both together the Text feature is very nice.
But: You Cannot use a whitespace between "Alt" and "Gr".

I like your tool btw xD

**Comment by monsterbrain** [comment]
Thanks a lot.

Could you please clarify your case of Alt and Gr, what output are you expecting? maybe I can help

**Comment by monsterbrain** [comment]
OK. Understood. Thanks. I'll check the issue then.

**Comment by monsterbrain** [comment]
@TsgabiXD - The issue has been fixed now. Please check.

**Comment by TsgabiXD** [comment]
Nice it works. Thank you very much!
